(u'10.6', u'10. Social protection', u'10.6 Housing')
(u'10.8', u'10. Social protection', u'10.8 R&D social protection')
(u'10.9', u'10. Social protection', u'10.9 Social protection n.e.c.')
(u'10.UKLA', u'10. Social protection', u'LA data sub_function')
(u'10.4.UKBEN', u'10. Social protection', u'of which: family benefits, income support and tax credits (family and children)')
(u'10.7.UKBEN', u'10. Social protection', u'of which: family benefits, income support and tax credits (social exclusion n.e.c.)')
(u'10.1', u'10. Social protection', u'of which: incapacity, disability and injury benefits')
(u'10.5.UKOTHER', u'10. Social protection', u'of which: other unemployment benefits')
(u'10.UKPEN', u'10. Social protection', u'of which: pensions')
(u'10.4', u'10. Social protection', u'of which: personal social services (family and children)')
(u'10.2', u'10. Social protection', u'of which: personal social services (old age)')
(u'10.1', u'10. Social protection', u'of which: personal social services (sickness and disability)')
(u'10.7', u'10. Social protection', u'of which: personal social services (social exclusion n.e.c.)')
(u'10.5', u'10. Social protection', u'of which: personal social services (unemployment)')
(u'10.UKWID', u'10. Social protection', u"of which: widow's benefits")
(u'02.1', u'2. Defence', u'2.1 Military defence')
(u'02.2', u'2. Defence', u'2.2 Civil defence')
(u'02.3', u'2. Defence', u'2.3 Foreign military aid')
(u'02.4', u'2. Defence', u'2.4 R&D defence')
(u'02.5', u'2. Defence', u'2.5 Defence n.e.c')
(u'02.UKLA', u'2. Defence', u'LA data sub_function')
(u'03.2', u'3. Public order and safety', u'3.2 Fire-protection services')
(u'03.3', u'3. Public order and safety', u'3.3 Law courts')
(u'03.4', u'3. Public order and safety', u'3.4 Prisons')
(u'03.5', u'3. Public order and safety', u'3.5 R&D public order and safety')
(u'03.6', u'3. Public order and safety', u'3.6 Public order and safety n.e.c.')
(u'03.UKLA', u'3. Public order and safety', u'LA data sub_function')
(u'03.UKIMM', u'3. Public order and safety', u'of which: immigration and citizenship')
(u'03.6.UKPOL', u'3. Public order and safety', u'of which: other police services')
(u'05.1', u'5. Environment protection', u'5.1 Waste management')
(u'05.2', u'5. Environment protection', u'5.2 Waste water management')
(u'05.3', u'5. Environment protection', u'5.3 Pollution abatement')
(u'05.4', u'5. Environment protection', u'5.4 Protection of biodiversity and landscape')
(u'05.5', u'5. Environment protection', u'5.5 R&D environment protection')
(u'05.6', u'5. Environment protection', u'5.6 Environment protection n.e.c')
(u'05.UKLA', u'5. Environment protection', u'LA data sub_function')
(u'06.2', u'6. Housing and community amenities', u'6.2 Community development')
(u'06.3', u'6. Housing and community amenities', u'6.3 Water supply')
(u'06.4', u'6. Housing and community amenities', u'6.4 Street lighting')
(u'06.5', u'6. Housing and community amenities', u'6.5 R&D housing and community amenities')
(u'06.6', u'6. Housing and community amenities', u'6.6 Housing and community amenities n.e.c')
(u'06.UKLA', u'6. Housing and community amenities', u'LA data sub_function')
(u'06.UKLA.HOUS', u'6. Housing and community amenities', u'of which: local authority housing')
(u'06.UKHOUS', u'6. Housing and community amenities', u'of which: other social housing')
(u'07.UKCEN', u'7. Health', u'Central and other health services')
(u'07.5', u'7. Health', u'Health research')
(u'07.UKLA', u'7. Health', u'LA data sub_function')
(u'07.UKSVC', u'7. Health', u'Medical services')
(u'08.1', u'8. Recreation, culture and religion', u'8.1 Recreational and sporting services')
(u'08.2', u'8. Recreation, culture and religion', u'8.2 Cultural services')
(u'08.3', u'8. Recreation, culture and religion', u'8.3 Broadcasting and publishing services')
(u'08.4', u'8. Recreation, culture and religion', u'8.4 Religious and other community services')
(u'08.5', u'8. Recreation, culture and religion', u'8.5 R&D recreation, culture and religion')
(u'08.6', u'8. Recreation, culture and religion', u'8.6 Recreation, culture and religion n.e.c')
(u'08.UKLA', u'8. Recreation, culture and religion', u'LA data sub_function')
(u'09.2', u'9. Education', u'9.2 Secondary education')
(u'09.3', u'9. Education', u'9.3 Post-secondary non-tertiary education')
(u'09.4', u'9. Education', u'9.4 Tertiary education')
(u'09.5', u'9. Education', u'9.5 Education not definable by level')
(u'09.6', u'9. Education', u'9.6 Subsidiary services to education')
(u'09.7', u'9. Education', u'9.7 R&D education')
(u'09.8', u'9. Education', u'9.8 Education n.e.c')
(u'09.UKLA', u'9. Education', u'LA data sub_function')
(u'09.1.1', u'9. Education', u'of which: primary education')
(u'09.1.2', u'9. Education', u'of which: under fives')
(u'01.8.UKCFSP', u'EU transactions', u'Attributed aid and CFSP')
(u'01.8.UKEC', u'EU transactions', u'EC receipts')
(u'01.2.UKGNI', u'EU transactions', u'GNI-based contribution (net of abatement and collection costs)')
(u'01.1.2.UKAME', u'Unallocated', u'AME margin')
(u'01.1.2.UKDEPT.', u'Unallocated', u'Departmental unallocated provision')
(u'01.1.2.UKRES', u'Unallocated', u'Reserve and other funds')
(u'04.2.UKLA', u'of which: agriculture, fisheries and forestry', u'LA data sub_function')
(u'04.2.2', u'of which: agriculture, fisheries and forestry', u'of which: forestry')
(u'04.2.UKCAP', u'of which: agriculture, fisheries and forestry', u'of which: market support under CAP')
(u'04.2.UKPOL', u'of which: agriculture, fisheries and forestry', u'of which: other agriculture, food and fisheries policy')
(u'04.1', u'of which: employment policies', u'4.1 General economic, commercial and labour affairs')
(u'04.1.UKLA', u'of which: employment policies', u'LA data sub_function')
(u'04.1', u'of which: enterprise and economic development', u'4.1 General economic, commercial and labour affairs')
(u'04.3', u'of which: enterprise and economic development', u'4.3 Fuel and energy')
(u'04.4', u'of which: enterprise and economic development', u'4.4 Mining, manufacturing and construction')
(u'04.6', u'of which: enterprise and economic development', u'4.6 Communication')
(u'04.7', u'of which: enterprise and economic development', u'4.7 Other Industries')
(u'04.9', u'of which: enterprise and economic development', u'4.9 Economic affairs n.e.c')
(u'04.UKLA', u'of which: enterprise and economic development', u'LA data sub_function')
(u'01.1', u'of which: international services', u'1.1 Executive and legislative organs, financial and fiscal affairs, external affairs')
(u'01.2', u'of which: international services', u'1.2 Foreign economic aid')
(u'01.1', u'of which: public and common services', u'1.1 Executive and legislative organs, financial and fiscal affairs, external affairs')
(u'01.3', u'of which: public and common services', u'1.3 General services')
(u'01.4', u'of which: public and common services', u'1.4 Basic research')
(u'01.5', u'of which: public and common services', u'1.5 R&D general public services')
(u'01.6', u'of which: public and common services', u'1.6 General public services n.e.c.')
(u'01.UKLA', u'of which: public and common services', u'LA data sub_function')
(u'01.7.UKCEN', u'of which: public sector debt interest', u'of which: central government debt interest')
(u'01.7.UKLA', u'of which: public sector debt interest', u'of which: local authority debt interest')
(u'01.7.UKCORP', u'of which: public sector debt interest', u'of which: public corporations debt interest')
(u'04.8', u'of which: science and technology', u'4.8 R&D economic affairs')
(u'04.5.UKLA', u'of which: transport', u'LA data sub_function')
(u'04.5.UKPUB.', u'of which: transport', u'of which: local public transport')
(u'04.5.1.UKLOC', u'of which: transport', u'of which: local roads')
(u'04.5.1.UKNAT', u'of which: transport', u'of which: national roads')
(u'04.5.5', u'of which: transport', u'of which: other transport')
(u'04.5.3', u'of which: transport', u'of which: railway')
